# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('marca', models.CharField(max_length=40)),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('marca_carro', models.CharField(max_length=40)),
                ('modelo_carro', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
