# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='empleado_ptr',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
