# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Marca')),
            ],
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='marca_carro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Marca'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='modelo_carro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Modelo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
