# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20151206_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='marca_carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Marca'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='modelo_carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Modelo'),
        ),
    ]
