# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20160122_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Marca'),
        ),
    ]
