# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20160123_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculonuevo',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
