# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_auto_20151119_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_documento', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_sangre', models.CharField(max_length=20)),
                ('experiencia', models.IntegerField()),
                ('jornada', models.CharField(max_length=15)),
                ('fecha_vinculacion', models.DateField()),
                ('cargo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('area', models.CharField(max_length=150)),
                ('estado_empleado', models.CharField(max_length=15)),
                ('jefe', models.IntegerField()),
            ],
        ),
    ]
