# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_vinculacion',
            field=models.DateField(blank=True),
        ),
    ]
