# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2016, 1, 16, 22, 14, 7, 990280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orden',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
