# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion', '0004_auto_20160122_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2016, 1, 23, 17, 13, 37, 556909, tzinfo=utc)),
        ),
    ]
