# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion', '0006_auto_20160123_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2016, 1, 23, 17, 39, 21, 659444, tzinfo=utc)),
        ),
    ]
